import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
// If MUI ships a v16 build for your setup, use this instead:
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";

import Providers from "./providers";
import { ToastProvider } from "@/components/toast/ToastProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Providers>
            <ToastProvider>
              {children}
            </ToastProvider>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
